version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - 80:80
    networks:
      backend:
        ipv4_address: 10.0.0.2
  users:
    build: ./services/users
    volumes:
      - ./services/users:/go/src/app
    depends_on:
      - proxy
    networks:
      backend:
        ipv4_address: 10.0.0.3
  posts:
    build: ./services/posts
    volumes:
      - ./services/users:/go/src/app
    depends_on:
      - proxy
    networks:
      backend:
        ipv4_address: 10.0.0.4

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16